In [1]:
import torch
import numpy as np 
from torch import nn
import matplotlib.pyplot as plt

c:\Users\suryansh\.conda\envs\cv\lib\site-packages\torch\_subclasses\functional_tensor.py:307: UserWarning: Failed to initialize NumPy: DLL load failed while importing _multiarray_umath: The specified module could not be found. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
random_seed = 42
tensor1 = torch.rand([3,4])
tensor2 = torch.rand([4,3])
print("tensor1:\n",tensor1,"\n" "tensor2:\n", tensor2)

tensor1:
 tensor([[0.3285, 0.4743, 0.2487, 0.1039],
        [0.2467, 0.1015, 0.9918, 0.8930],
        [0.4596, 0.2470, 0.7713, 0.3145]]) 
tensor2:
 tensor([[0.4573, 0.1985, 0.8393],
        [0.5394, 0.7837, 0.7573],
        [0.6642, 0.6901, 0.6982],
        [0.8183, 0.4073, 0.0295]])


In [3]:
torch.matmul(tensor1, tensor2)

tensor([[0.6563, 0.6509, 0.8117],
        [1.5572, 1.1767, 1.0028],
        [1.1131, 0.9452, 1.1206]])

In [4]:
torch.cuda.is_available()

True

In [5]:
x= torch.arange(-5, 5, 0.1).view(-1,1)
w = 0.02
b = 0.3

y = w*x + b

print(x, y)

tensor([[-5.0000e+00],
        [-4.9000e+00],
        [-4.8000e+00],
        [-4.7000e+00],
        [-4.6000e+00],
        [-4.5000e+00],
        [-4.4000e+00],
        [-4.3000e+00],
        [-4.2000e+00],
        [-4.1000e+00],
        [-4.0000e+00],
        [-3.9000e+00],
        [-3.8000e+00],
        [-3.7000e+00],
        [-3.6000e+00],
        [-3.5000e+00],
        [-3.4000e+00],
        [-3.3000e+00],
        [-3.2000e+00],
        [-3.1000e+00],
        [-3.0000e+00],
        [-2.9000e+00],
        [-2.8000e+00],
        [-2.7000e+00],
        [-2.6000e+00],
        [-2.5000e+00],
        [-2.4000e+00],
        [-2.3000e+00],
        [-2.2000e+00],
        [-2.1000e+00],
        [-2.0000e+00],
        [-1.9000e+00],
        [-1.8000e+00],
        [-1.7000e+00],
        [-1.6000e+00],
        [-1.5000e+00],
        [-1.4000e+00],
        [-1.3000e+00],
        [-1.2000e+00],
        [-1.1000e+00],
        [-1.0000e+00],
        [-9.0000e-01],
        [-8.0000e-01],
        [-7

In [6]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        
        #define weights for the regression
        self.weights = nn.Parameter(torch.randn(1,
                                                requires_grad=True, #parameter to be updated by gradient descent enabled
                                                dtype=torch.float))
        #define bias of the regression      
        self.bias = nn.Parameter(torch.randn(1,
                                             requires_grad=True, 
                                             dtype=torch.float))
        
    #forward method to define the computation 
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.weights * x + self.bias  #main formula for linear regression 


In [7]:
torch.manual_seed(42)

model0 = LinearRegression()

list(model0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [8]:
model0.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [9]:
with torch.inference_mode():
    y_pred = model0(x)

y_pred

tensor([[-1.5546],
        [-1.5210],
        [-1.4873],
        [-1.4536],
        [-1.4200],
        [-1.3863],
        [-1.3526],
        [-1.3190],
        [-1.2853],
        [-1.2516],
        [-1.2180],
        [-1.1843],
        [-1.1506],
        [-1.1169],
        [-1.0833],
        [-1.0496],
        [-1.0159],
        [-0.9823],
        [-0.9486],
        [-0.9149],
        [-0.8813],
        [-0.8476],
        [-0.8139],
        [-0.7803],
        [-0.7466],
        [-0.7129],
        [-0.6792],
        [-0.6456],
        [-0.6119],
        [-0.5782],
        [-0.5446],
        [-0.5109],
        [-0.4772],
        [-0.4436],
        [-0.4099],
        [-0.3762],
        [-0.3426],
        [-0.3089],
        [-0.2752],
        [-0.2415],
        [-0.2079],
        [-0.1742],
        [-0.1405],
        [-0.1069],
        [-0.0732],
        [-0.0395],
        [-0.0059],
        [ 0.0278],
        [ 0.0615],
        [ 0.0951],
        [ 0.1288],
        [ 0.1625],
        [ 0.

In [10]:
y

tensor([[0.2000],
        [0.2020],
        [0.2040],
        [0.2060],
        [0.2080],
        [0.2100],
        [0.2120],
        [0.2140],
        [0.2160],
        [0.2180],
        [0.2200],
        [0.2220],
        [0.2240],
        [0.2260],
        [0.2280],
        [0.2300],
        [0.2320],
        [0.2340],
        [0.2360],
        [0.2380],
        [0.2400],
        [0.2420],
        [0.2440],
        [0.2460],
        [0.2480],
        [0.2500],
        [0.2520],
        [0.2540],
        [0.2560],
        [0.2580],
        [0.2600],
        [0.2620],
        [0.2640],
        [0.2660],
        [0.2680],
        [0.2700],
        [0.2720],
        [0.2740],
        [0.2760],
        [0.2780],
        [0.2800],
        [0.2820],
        [0.2840],
        [0.2860],
        [0.2880],
        [0.2900],
        [0.2920],
        [0.2940],
        [0.2960],
        [0.2980],
        [0.3000],
        [0.3020],
        [0.3040],
        [0.3060],
        [0.3080],
        [0

In [11]:
lossFn = nn.MSELoss()

optimizer = torch.optim.SGD(model0.parameters(), lr = 0.01)

epochs = 1000

In [12]:
for epoch in range(epochs):

    y_pred = model0(x)

    loss = lossFn(y_pred, y)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    if epoch % 100 == 0:
        print("epoch", {epoch}, "| loss" , loss.item())
        print("weight", model0.weights.item())
        print("bias", model0.bias.item())

epoch {0} | loss 0.8706680536270142
weight 0.28372690081596375
bias 0.13254991173744202
epoch {100} | loss 0.0005030250758863986
weight 0.01985015906393528
bias 0.27801695466041565
epoch {200} | loss 8.859999070409685e-06
weight 0.019980113953351974
bias 0.2970825135707855
epoch {300} | loss 1.5600271296989376e-07
weight 0.019997362047433853
bias 0.2996128797531128
epoch {400} | loss 2.7380453460068566e-09
weight 0.01999964751303196
bias 0.29994872212409973
epoch {500} | loss 4.8620218962014405e-11
weight 0.019999952986836433
bias 0.2999931871891022
epoch {600} | loss 8.002998220721369e-13
weight 0.019999990239739418
bias 0.2999991476535797
epoch {700} | loss 5.111288996217933e-13
weight 0.019999990239739418
bias 0.29999929666519165
epoch {800} | loss 5.111288996217933e-13
weight 0.019999990239739418
bias 0.29999929666519165
epoch {900} | loss 5.111288996217933e-13
weight 0.019999990239739418
bias 0.29999929666519165


In [ ]:
loss_value = []
epoch_value = []

loss_value.append(loss.item())
epoch_value.append(epoch)

: 

In [ ]:
plt.plot(epoch_value, loss_value)